export const RES_LIST_REQUEST = 'RES_LIST_REQUEST';
export const RES_LIST_SUCCESS = 'RES_LIST_SUCCESS';
export const RES_LIST_FAIL = 'RES_LIST_FAIL';

export const RES_DETAILS_REQUEST = 'RES_DETAILS_REQUEST';
export const RES_DETAILS_SUCCESS = 'RES_DETAILS_SUCCESS';
export const RES_DETAILS_FAIL = 'RES_DETAILS_FAIL';

export const RES_SAVE_FAIL = 'RES_SAVE_FAIL';
export const RES_SAVE_SUCCESS = 'RES_SAVE_SUCCESS';
export const RES_SAVE_REQUEST = 'RES_SAVE_REQUEST'

export const RES_DELETE_FAIL = 'RES_DELETE_FAIL';
export const RES_DELETE_SUCCESS = 'RES_DELETE_SUCCESS';
export const RES_DELETE_REQUEST = 'RES_DELETE_REQUEST'