export const RESTAU_LIST_REQUEST = 'RESTAU_LIST_REQUEST';
export const RESTAU_LIST_SUCCESS = 'RESTAU_LIST_SUCCESS';
export const RESTAU_LIST_FAIL = 'RESTAU_LIST_FAIL';

export const RESTAU_DETAILS_REQUEST = 'RESTAU_DETAILS_REQUEST';
export const RESTAU_DETAILS_SUCCESS = 'RESTAU_DETAILS_SUCCESS';
export const RESTAU_DETAILS_FAIL = 'RESTAU_DETAILS_FAIL';

export const RESTAU_SAVE_FAIL = 'RESTAU_SAVE_FAIL';
export const RESTAU_SAVE_SUCCESS = 'RESTAU_SAVE_SUCCESS';
export const RESTAU_SAVE_REQUEST = 'RESTAU_SAVE_REQUEST'

export const RESTAU_DELETE_FAIL = 'RESTAU_DELETE_FAIL';
export const RESTAU_DELETE_SUCCESS = 'RESTAU_DELETE_SUCCESS';
export const RESTAU_DELETE_REQUEST = 'RESTAU_DELETE_REQUEST'